import type { LocalizedLabel, TrainingUnit } from "./types";

export type TrainingDomain = "boxing" | "strength";
export type DrillCategory = "fundamentals" | "footwork" | "offense" | "defense" | "equipment" | "conditioning" | "chest" | "back" | "legs" | "shoulders" | "core";
export interface Drill { id: string; domain: TrainingDomain; category: DrillCategory; name: LocalizedLabel; cue: LocalizedLabel; defaultUnit: TrainingUnit; defaultQuantity: number; }
const d = (id: string, category: DrillCategory, zhTW: string, en: string, cueZh: string, cueEn: string, defaultUnit: TrainingUnit = "rounds", defaultQuantity = 3, domain: TrainingDomain = "boxing"): Drill => ({ id, domain, category, name: { zhTW, en }, cue: { zhTW: cueZh, en: cueEn }, defaultUnit, defaultQuantity });
export const drillCategories: DrillCategory[] = ["fundamentals", "footwork", "offense", "defense", "equipment", "conditioning", "chest", "back", "legs", "shoulders", "core"];
export const drillLibrary: Drill[] = [
 d("stance","fundamentals","站架","Stance","重心在腳掌中心","Balance on mid-foot","minutes",5), d("guard","fundamentals","護手","Guard","下巴收、手回位","Chin tucked, hands return","minutes",5), d("skipping","fundamentals","跳繩","Skipping","輕快、穩定節奏","Light, steady rhythm","minutes",10), d("shadow","fundamentals","影子拳擊","Shadow Boxing","慢速且有目的","Slow and intentional"),
 d("step-forward","footwork","前進步法","Step Forward","前腳先、站架不變","Lead foot first"), d("step-back","footwork","後退步法","Step Back","後腳先、保持距離","Rear foot first"), d("lateral-slide","footwork","側移","Lateral Slide","腳不交叉、不併攏","Do not cross feet"), d("pivot","footwork","轉樞","Pivot","組合後轉出角度","Exit at an angle"),
 d("jab","offense","刺拳","Jab","直線出、直線回","Straight out, straight back"), d("cross","offense","直拳","Cross","後腳跟與髖帶動","Turn heel and hip"), d("hook","offense","勾拳","Hook","手肘與肩同高","Elbow level with shoulder"), d("uppercut","offense","上勾拳","Uppercut","微下沉再上頂","Dip then rise"), d("one-two","offense","1-2 組合","1-2 Combination","打完退一步","Step out after the combination"), d("one-two-three","offense","1-2-3 組合","1-2-3 Combination","出拳後保持護手","Guard after every shot"),
 d("high-guard","defense","高護手","High Guard","肘收、視線越過手套","Elbows in, eyes over gloves"), d("parry","defense","拍擋","Parry","小幅度帶開刺拳","Redirect, do not swat"), d("slip","defense","閃躲","Slip","靠腿和核心移動","Move with legs and core"), d("roll","defense","搖避","Roll","下沉穿過對手拳線","Dip under the punch line"), d("pull-back","defense","後撤","Pull Back","保有站架與回擊距離","Keep balance to return"),
 d("heavy-bag","equipment","沙包技術回合","Heavy Bag Technique","力量控制在六成","Keep power at sixty percent"), d("double-end","equipment","雙端球","Double-end Bag","先準確、再加速","Accuracy before speed"), d("slip-rope","equipment","繩下閃躲","Slip Rope","膝蓋下沉、不彎腰","Bend knees, not waist"), d("padwork","equipment","手靶","Padwork","帶著當日技術重點","Bring one technical focus"),
 d("core-circuit","conditioning","拳擊核心循環","Boxing Core Circuit","抗旋轉與傳力","Resist rotation and transfer force","minutes",10), d("zone-two","conditioning","Zone 2 跑","Zone 2 Run","能完整講一句話","Able to speak a full sentence","minutes",30), d("round-intervals","conditioning","回合跑","Round Intervals","跑三分、走一分","Run 3, walk 1","rounds",4), d("mobility","conditioning","收操伸展","Mobility Cooldown","肩、胸、髖活動度","Shoulders, chest, hips","minutes",10),
 d("bench-press","chest","槓鈴臥推","Barbell Bench Press","肩胛後收、雙腳穩定踩地","Set shoulders, feet planted","rounds",3,"strength"), d("incline-dumbbell-press","chest","上斜啞鈴臥推","Incline Dumbbell Press","手肘略低於肩線","Elbows slightly below shoulders","rounds",3,"strength"), d("cable-fly","chest","滑輪夾胸","Cable Fly","控制離心、胸肌收緊","Control the eccentric","rounds",3,"strength"),
 d("barbell-row","back","槓鈴划船","Barbell Row","軀幹固定、手肘往後帶","Brace torso, drive elbows back","rounds",3,"strength"), d("lat-pulldown","back","高位下拉","Lat Pulldown","胸口向上、拉向鎖骨","Chest up, pull to collarbone","rounds",3,"strength"), d("seated-row","back","坐姿划船","Seated Cable Row","肩膀放下再拉","Keep shoulders down","rounds",3,"strength"),
 d("back-squat","legs","槓鈴深蹲","Back Squat","膝蓋跟隨腳尖方向","Knees track toes","rounds",3,"strength"), d("romanian-deadlift","legs","羅馬尼亞硬舉","Romanian Deadlift","髖部後推、背保持中立","Hips back, neutral spine","rounds",3,"strength"), d("split-squat","legs","保加利亞分腿蹲","Bulgarian Split Squat","前腳踩穩、膝蓋穩定","Plant the lead foot","rounds",3,"strength"),
 d("overhead-press","shoulders","站姿肩推","Overhead Press","肋骨收好、推過頭頂","Ribs down, press overhead","rounds",3,"strength"), d("lateral-raise","shoulders","側平舉","Lateral Raise","輕重量控制高度","Use control over load","rounds",3,"strength"), d("face-pull","shoulders","面拉","Face Pull","拉向眉間、手肘外開","Pull to eyebrow level","rounds",3,"strength"),
 d("pallof-press","core","Pallof 抗旋轉推","Pallof Press","骨盆保持正、不要旋轉","Resist rotation","rounds",3,"strength"), d("dead-bug","core","死蟲式","Dead Bug","下背貼地、慢慢伸展","Low back stays down","rounds",3,"strength"), d("farmer-carry","core","農夫走路","Farmer Carry","握緊、軀幹直立","Grip tight, stand tall","minutes",3,"strength"),
];
export function filterDrills(drills: Drill[], options: { query: string; domain: TrainingDomain; category: DrillCategory | "all"; favoriteIds: string[]; favoritesOnly: boolean }) { const q = options.query.trim().toLowerCase(); return drills.filter((drill) => drill.domain === options.domain && (options.category === "all" || drill.category === options.category) && (!options.favoritesOnly || options.favoriteIds.includes(drill.id)) && (!q || [drill.name.en, drill.name.zhTW].some((name) => name.toLowerCase().includes(q)))); }
