import type { Drill, DrillCategory, EquipmentType } from "./drills";

const strength = (
  id: string,
  category: DrillCategory,
  zhTW: string,
  en: string,
  equipment: EquipmentType,
  imageUrl: string,
  searchTerms: string[],
  defaultUnit: Drill["defaultUnit"] = "rounds",
  defaultQuantity = 3,
): Drill => ({
  id,
  domain: "strength",
  category,
  name: { zhTW, en },
  cue: { zhTW: "保持穩定並控制回程", en: "Stay stable and control the return" },
  defaultUnit,
  defaultQuantity,
  equipment,
  imageUrl,
  imageSource: "wger",
  searchTerms,
});

const cardioImage = (fileName: string) => import.meta.env.BASE_URL + "cardio/" + fileName;

const cardio = (id: string, zhTW: string, en: string, imageUrl: string, searchTerms: string[], quantity = 20): Drill => ({
  id,
  domain: "strength",
  category: "cardio",
  name: { zhTW, en },
  cue: { zhTW: "維持可控制的節奏", en: "Keep a sustainable pace" },
  defaultUnit: "minutes",
  defaultQuantity: quantity,
  imageUrl,
  imageSource: "Corner cardio illustration",
  searchTerms,
});

export const strengthLibrary: Drill[] = [
  strength("bench-press", "chest", "槓鈴臥推", "Barbell Bench Press", "barbell", "https://wger.de/media/exercise-images/192/Bench-press-1.png", ["臥推", "bench", "chest"]),
  strength("incline-dumbbell-press", "chest", "上斜啞鈴臥推", "Incline Dumbbell Press", "dumbbell", "https://wger.de/media/exercise-images/16/Incline-press-1.png", ["上斜", "臥推", "incline"]),
  strength("cable-fly", "chest", "滑輪夾胸", "Cable Fly", "cable", "https://wger.de/media/exercise-images/1922/eb750ee5-3220-4128-aef1-5e2f1ccff40a.webp", ["夾胸", "飛鳥", "fly"]),
  strength("dumbbell-bench-press", "chest", "啞鈴臥推", "Dumbbell Bench Press", "dumbbell", "https://wger.de/media/exercise-images/97/Dumbbell-bench-press-1.png", ["臥推", "bench", "chest"]),
  strength("incline-barbell-press", "chest", "上斜槓鈴臥推", "Incline Barbell Press", "barbell", "https://wger.de/media/exercise-images/41/Incline-bench-press-1.png", ["上斜", "臥推", "incline"]),
  strength("chest-press-machine", "chest", "機械胸推", "Machine Chest Press", "machine", "https://wger.de/media/exercise-images/129/b263c968-e067-4750-916a-d8758a7df23e.webp", ["胸推", "machine", "chest"]),
  strength("parallel-bar-dips", "chest", "雙槓撐體", "Parallel Bar Dips", "bodyweight", "https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png", ["雙槓", "dips", "chest"]),
  strength("hammer-chest-press", "chest", "悍馬下斜胸推", "Hammer Strength Chest Press", "hammer", "https://wger.de/media/exercise-images/1831/2d9d509f-707b-4132-961e-91a2459ca198.jpg", ["悍馬", "胸推", "hammer"]),
  strength("barbell-row", "back", "槓鈴划船", "Barbell Row", "barbell", "https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png", ["划船", "row", "back"]),
  strength("lat-pulldown", "back", "高位下拉", "Lat Pulldown", "cable", "https://wger.de/media/exercise-images/1127/4942b7c0-6bda-4983-88e5-86547c3d445e.png", ["下拉", "pulldown", "back"]),
  strength("seated-row", "back", "坐姿划船", "Seated Cable Row", "cable", "https://wger.de/media/exercise-images/1117/2555c4c3-a84d-47db-b83b-cbf721f12e45.png", ["划船", "row", "背部"]),
  strength("deadlift", "back", "傳統硬舉", "Deadlift", "barbell", "https://wger.de/media/exercise-images/184/1709c405-620a-4d07-9658-fade2b66a2df.jpeg", ["硬舉", "deadlift", "back"]),
  strength("pull-up", "back", "引體向上", "Pull-up", "bodyweight", "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg", ["引體", "pullup", "back"]),
  strength("t-bar-row", "back", "T 槓划船", "T-Bar Row", "barbell", "https://wger.de/media/exercise-images/106/T-bar-row-1.png", ["划船", "row", "back"]),
  strength("one-arm-dumbbell-row", "back", "單臂啞鈴划船", "One-arm Dumbbell Row", "dumbbell", "https://wger.de/media/exercise-images/1186/1987a039-cf35-437e-bbdc-40c53dd7d053.jpg", ["單臂", "划船", "row"]),
  strength("straight-arm-pulldown", "back", "直臂下拉", "Straight-arm Pulldown", "cable", "https://wger.de/media/exercise-images/1726/2e7e541b-5f55-405a-ae78-3e71b3f42db4.png", ["直臂", "下拉", "pulldown"]),
  strength("back-squat", "legs", "槓鈴深蹲", "Back Squat", "barbell", "https://wger.de/media/exercise-images/1801/60043328-1cfb-4289-9865-aaf64d5aaa28.jpg", ["深蹲", "squat", "腿"]),
  strength("romanian-deadlift", "legs", "羅馬尼亞硬舉", "Romanian Deadlift", "dumbbell", "https://wger.de/media/exercise-images/1652/0306c8c0-70cc-45d4-92de-6fa72ceaa834.webp", ["硬舉", "rdl", "腿後側"]),
  strength("split-squat", "legs", "保加利亞分腿蹲", "Bulgarian Split Squat", "dumbbell", "https://wger.de/media/exercise-images/988/6283b258-a4d7-4833-84f7-a38987022d3d.png", ["保加利亞", "分腿蹲", "bulgarian"]),
  strength("goblet-squat", "legs", "高腳杯深蹲", "Goblet Squat", "kettlebell", "https://wger.de/media/exercise-images/203/1c052351-2af0-4227-aeb0-244008e4b0a8.jpeg", ["高腳杯", "深蹲", "goblet"]),
  strength("front-squat", "legs", "前蹲", "Front Squat", "barbell", "https://wger.de/media/exercise-images/191/Front-squat-1-857x1024.png", ["前蹲", "深蹲", "squat"]),
  strength("leg-press", "legs", "腿推", "Leg Press", "machine", "https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp", ["腿推", "leg press", "legs"]),
  strength("walking-lunge", "legs", "行走弓箭步", "Walking Lunge", "bodyweight", "https://wger.de/media/exercise-images/113/Walking-lunges-1.png", ["弓箭步", "lunge", "legs"]),
  strength("dumbbell-hip-thrust", "legs", "啞鈴臀推", "Dumbbell Hip Thrust", "dumbbell", "https://wger.de/media/exercise-images/1642/a81ad922-caf5-47f8-99b4-640cb0717436.webp", ["臀推", "hip thrust", "glutes"]),
  strength("leg-curl", "legs", "腿後勾", "Leg Curl", "machine", "https://wger.de/media/exercise-images/154/lying-leg-curl-machine-large-1.png", ["腿後勾", "leg curl", "hamstrings"]),
  strength("leg-extension", "legs", "腿伸展", "Leg Extension", "machine", "https://wger.de/media/exercise-images/369/78c915d1-e46d-4d30-8124-65d68664c3ef.png", ["腿伸展", "leg extension", "quads"]),
  strength("kettlebell-swing", "legs", "壺鈴擺盪", "Kettlebell Swing", "kettlebell", "https://wger.de/media/exercise-images/960/da4d0560-da89-4bb5-b91f-746458fb04ad.png", ["壺鈴", "擺盪", "swing"]),
  strength("pistol-squat", "legs", "單腳深蹲", "Pistol Squat", "bodyweight", "https://wger.de/media/exercise-images/456/3b681e59-377b-40db-9113-ca5873ce084b.jpg", ["單腳", "深蹲", "pistol"]),
  strength("overhead-press", "shoulders", "站姿肩推", "Overhead Press", "barbell", "https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png", ["肩推", "press", "shoulder"]),
  strength("lateral-raise", "shoulders", "側平舉", "Dumbbell Lateral Raise", "dumbbell", "https://wger.de/media/exercise-images/148/lateral-dumbbell-raises-large-2.png", ["側平舉", "lateral", "shoulder"]),
  strength("face-pull", "shoulders", "面拉", "Face Pull", "cable", "https://wger.de/media/exercise-images/1732/d13b9adb-968e-4f73-95e6-b16690bcf616.jpg", ["面拉", "facepull", "rear delt"]),
  strength("dumbbell-shoulder-press", "shoulders", "啞鈴肩推", "Dumbbell Shoulder Press", "dumbbell", "https://wger.de/media/exercise-images/123/dumbbell-shoulder-press-large-1.png", ["肩推", "press", "shoulder"]),
  strength("rear-delt-raise", "shoulders", "反向飛鳥", "Rear Delt Raise", "dumbbell", "https://wger.de/media/exercise-images/487/ad724e5c-b1ed-49e8-9279-a17545b0dd0b.png", ["反向飛鳥", "rear delt", "shoulder"]),
  strength("barbell-shrug", "shoulders", "槓鈴聳肩", "Barbell Shrug", "barbell", "https://wger.de/media/exercise-images/150/Barbell-shrugs-1.png", ["聳肩", "shrug", "traps"]),
  strength("pike-push-up", "shoulders", "派克伏地挺身", "Pike Push-up", "bodyweight", "https://wger.de/media/exercise-images/454/447f3c17-405f-46e0-b138-65c2a8caaab0.png", ["派克", "伏地", "shoulder"]),
  strength("barbell-curl", "arms", "槓鈴彎舉", "Barbell Curl", "barbell", "https://wger.de/media/exercise-images/74/Bicep-curls-1.png", ["彎舉", "curl", "biceps"]),
  strength("hammer-curl", "arms", "槌式彎舉", "Hammer Curl", "dumbbell", "https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png", ["槌式", "彎舉", "curl"]),
  strength("triceps-pushdown", "arms", "繩索下壓", "Triceps Pushdown", "cable", "https://wger.de/media/exercise-images/1185/c5ca283d-8958-4fd8-9d59-a3f52a3ac66b.jpg", ["三頭", "下壓", "triceps"]),
  strength("skullcrusher", "arms", "仰臥臂屈伸", "Skullcrusher", "barbell", "https://wger.de/media/exercise-images/84/Lying-close-grip-triceps-press-to-chin-1.png", ["臂屈伸", "三頭", "triceps"]),
  strength("dumbbell-curl", "arms", "啞鈴彎舉", "Dumbbell Curl", "dumbbell", "https://wger.de/media/exercise-images/81/Biceps-curl-1.png", ["啞鈴", "彎舉", "curl"]),
  strength("cable-curl", "arms", "繩索彎舉", "Cable Curl", "cable", "https://wger.de/media/exercise-images/912/e10a034f-6370-4dd6-b1c2-416b27844529.png", ["繩索", "彎舉", "curl"]),
  strength("overhead-triceps-extension", "arms", "過頭三頭伸展", "Overhead Triceps Extension", "dumbbell", "https://wger.de/media/exercise-images/1519/fab7f641-27d4-40b5-8edd-1a0a137bfd94.gif", ["過頭", "三頭", "triceps"]),
  strength("plank", "core", "棒式", "Plank", "bodyweight", "https://wger.de/media/exercise-images/458/b7bd9c28-9f1d-4647-bd17-ab6a3adf5770.png", ["棒式", "plank", "core"], "minutes", 1),
  strength("ab-rollout", "core", "滾腹輪", "Ab Rollout", "bodyweight", "https://wger.de/media/exercise-images/41/34b37423-269f-43d4-9d29-d2a90eeaa6b4.png", ["滾腹輪", "ab wheel", "core"]),
  strength("russian-twist", "core", "俄羅斯轉體", "Russian Twist", "bodyweight", "https://wger.de/media/exercise-images/1193/70ca5d80-3847-4a8c-8882-c6e9e485e29e.png", ["轉體", "twist", "core"]),
  strength("bird-dog", "core", "鳥狗式", "Bird Dog", "bodyweight", "https://wger.de/media/exercise-images/1572/3d14e761-a73d-49da-8804-f3016a7573ff.png", ["鳥狗", "core", "stability"]),
  strength("pallof-press", "core", "Pallof 抗旋轉推", "Pallof Press", "cable", "https://wger.de/media/exercise-images/1194/074e1766-4208-4a67-a211-9721772d99b0.png", ["抗旋轉", "core", "pallof"]),
  strength("medicine-ball-twist", "core", "藥球轉體", "Medicine Ball Twist", "bodyweight", "https://wger.de/media/exercise-images/1089/49f51716-535d-41dd-aeb5-cff5bb906bc1.jpeg", ["藥球", "轉體", "core"]),
  strength("standing-calf-raise", "calves", "站姿提踵", "Standing Calf Raise", "bodyweight", "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg", ["提踵", "calf", "小腿"]),
  strength("seated-calf-raise", "calves", "坐姿提踵", "Seated Calf Raise", "machine", "https://wger.de/media/exercise-images/1243/53d4fabe-c994-4907-873f-8d82813a9832.png", ["坐姿", "提踵", "calf"]),
  cardio("cardio-run", "跑步", "Running", cardioImage("running.png"), ["跑步", "run", "running"], 30),
  cardio("cardio-cycle", "室內單車", "Cycling", cardioImage("cycling.png"), ["單車", "cycling", "bike"], 30),
  cardio("cardio-rower", "划船機", "Rowing Machine", cardioImage("rowing.png"), ["划船機", "rower", "cardio"], 20),
  cardio("cardio-jump-rope", "跳繩有氧", "Jump Rope", cardioImage("jump-rope.png"), ["跳繩", "jump rope", "cardio"], 15),
  cardio("cardio-stairs", "爬樓機", "Stair Climber", cardioImage("stairs.png"), ["爬樓", "stairs", "cardio"], 20),
  cardio("cardio-swim", "游泳", "Swimming", cardioImage("swimming.png"), ["游泳", "swimming", "cardio"], 30),
  cardio("cardio-interval", "間歇訓練", "Cardio Intervals", cardioImage("intervals.png"), ["間歇", "interval", "hiit"], 20),
];

